version: '3.8'

services:
  common_database_server:
    image: mariadb:10.11
    container_name: common_database_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - comm_db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - web_services_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: common_phpmyadmin
    restart: always
    ports:
      - "9001:80"
    environment:
      - PMA_HOST=common_database_server
    networks:
      - web_services_network
    depends_on:
      - common_database_server

volumes:
  comm_db_data:

networks:
  web_services_network:
    driver: bridge
    # ⬇️ 이 부분을 추가해주세요!
    name: web_services_network