# File: docker-compose.yml
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: favorites_web
    ports:
      - "9030:80"
    volumes:
      - ./app:/var/www/html
    networks:
      - web_services_network

networks:
  web_services_network:
    external: true